name: "dockerhub-doom"

on: push

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: ./.github/actions/deploy
        with: 
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/doom:latest
