name: "dockerhub-doom"

on: push

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with: 
          context: ./.github/actions/deploy/
          file: ./Dockerfile
          push: true
          tags: user/doom:latest
